name: BuildLuajit

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r15c

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt install make -y
          sudo apt install clang -y
          set NDK=${ANDROID_NDK_ROOT}
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./mk-luajit.sh arm64-v8a
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: libluajit.so
